on:
  workflow_run:
    workflows: ["Custom Deploy"]
    types:
      - completed

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:17
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: node emails/send.js
        env:
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
